## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
0,0,Castro,CL,2019-08-26 17:25:49,-42.48,-73.76,48.20,61,40,14.99,scattered clouds,0.000,0
1,1,Lebu,ET,2019-08-26 17:25:49,8.96,38.73,58.69,83,72,1.45,light rain,2.187,0
2,2,Sitka,US,2019-08-26 17:25:49,37.17,-99.65,90.00,46,6,21.00,clear sky,0.000,0
3,3,Torbay,CA,2019-08-26 17:25:49,47.66,-52.73,75.00,43,20,10.29,few clouds,0.000,0
4,4,Grandview,US,2019-08-26 17:25:50,38.89,-94.53,69.80,93,40,4.70,heavy intensity rain,0.000,0

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is your desired minimum temperature for your trip? "))
max_temp = float(input("What is your desired maximum temperature for your trip? "))

What is your desired minimum temperature for your trip? 70
What is your desired maximum temperature for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) &
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
2,2,Sitka,US,2019-08-26 17:25:49,37.17,-99.65,90.00,46,6,21.00,clear sky,0.0,0
3,3,Torbay,CA,2019-08-26 17:25:49,47.66,-52.73,75.00,43,20,10.29,few clouds,0.0,0
6,6,Cidreira,BR,2019-08-26 17:25:50,-30.17,-50.22,72.01,50,48,3.44,scattered clouds,0.0,0
7,7,Hilo,US,2019-08-26 17:25:50,19.71,-155.08,75.20,88,90,4.70,heavy intensity rain,0.0,0
14,14,Puerto Ayora,EC,2019-08-26 17:25:52,-0.74,-90.35,78.80,65,20,16.11,few clouds,0.0,0
15,15,Avera,US,2019-08-26 17:25:53,33.19,-82.53,86.00,69,75,5.82,broken clouds,0.0,0
17,17,Kapaa,US,2019-08-26 17:25:54,22.08,-159.32,82.40,69,75,20.80,broken clouds,0.0,0
19,19,Rock Sound,BS,2019-08-26 17:24:12,24.90,-76.20,84.43,76,85,9.91,overcast clouds,0.0,0
20,20,Faribault,US,2019-08-26 17:25:55,44.30,-93.27,71.01,77,90,8.05,light rain,0.0,0
23,23,Fazilka,IN,2019-08-26 17:25:56,30.41,74.03,86.59,55,68,5.84,broken clouds,0.0,0

In [5]:
# 4a. Determine if there are any empty rows.

preferred_cities_df.isnull().sum()

City_ID                     0
City                        0
Country                     1
Date                        0
Lat                         0
Lng                         0
Max Temp                    0
Humidity                    0
Cloudiness                  0
Wind Speed                  0
Current Description         0
Rain inches (last 3 hrs)    0
Snow inches (last 3 hrs)    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()
clean_df

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description,Rain inches (last 3 hrs),Snow inches (last 3 hrs)
2,2,Sitka,US,2019-08-26 17:25:49,37.17,-99.65,90.00,46,6,21.00,clear sky,0.0,0
3,3,Torbay,CA,2019-08-26 17:25:49,47.66,-52.73,75.00,43,20,10.29,few clouds,0.0,0
6,6,Cidreira,BR,2019-08-26 17:25:50,-30.17,-50.22,72.01,50,48,3.44,scattered clouds,0.0,0
7,7,Hilo,US,2019-08-26 17:25:50,19.71,-155.08,75.20,88,90,4.70,heavy intensity rain,0.0,0
14,14,Puerto Ayora,EC,2019-08-26 17:25:52,-0.74,-90.35,78.80,65,20,16.11,few clouds,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
558,558,Saint-Augustin,CA,2019-08-26 17:28:26,45.63,-73.98,80.01,47,20,6.93,few clouds,0.0,0
561,561,Deep River,CA,2019-08-26 17:28:27,46.10,-77.49,78.01,60,20,8.03,few clouds,0.0,0
562,562,Port-Gentil,GA,2019-08-26 17:28:27,-0.72,8.78,78.80,83,75,10.29,broken clouds,0.0,0
563,563,Eureka,US,2019-08-26 17:28:27,40.80,-124.16,73.00,68,1,3.36,haze,0.0,0
564,564,Moen,BE,2019-08-26 17:28:28,50.77,3.40,90.00,40,0,5.82,clear sky,0.0,0

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
2,Sitka,US,90.00,clear sky,37.17,-99.65,
3,Torbay,CA,75.00,few clouds,47.66,-52.73,
6,Cidreira,BR,72.01,scattered clouds,-30.17,-50.22,
7,Hilo,US,75.20,heavy intensity rain,19.71,-155.08,
14,Puerto Ayora,EC,78.80,few clouds,-0.74,-90.35,
15,Avera,US,86.00,broken clouds,33.19,-82.53,
17,Kapaa,US,82.40,broken clouds,22.08,-159.32,
19,Rock Sound,BS,84.43,overcast clouds,24.90,-76.20,
20,Faribault,US,71.01,light rain,44.30,-93.27,
23,Fazilka,IN,86.59,broken clouds,30.41,74.03,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        
    except (IndexError):
        print("Hotel not found...Skipping.")

Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.
Hotel not found...Skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.loc[(hotel_df["Hotel Name"]!='')]
clean_hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Torbay,CA,75.00,few clouds,47.66,-52.73,See The Sea
6,Cidreira,BR,72.01,scattered clouds,-30.17,-50.22,Hotel Castelo
7,Hilo,US,75.20,heavy intensity rain,19.71,-155.08,SCP Hilo Hotel
14,Puerto Ayora,EC,78.80,few clouds,-0.74,-90.35,Finch Bay Galapagos Hotel
17,Kapaa,US,82.40,broken clouds,22.08,-159.32,Sheraton Kauai Coconut Beach Resort

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_vacation.csv"

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
print(g_key)

AIzaSyBU-ZzlNNrCpI5HzMcFAUIo-2xU3G0x35A